[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_20', 'phpExtensions.mbstring', 'phpExtensions.pdo']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'php artisan storage:link || true'
]

[phases.build]
cmds = [
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[start]
cmd = 'bash start.sh'